#!/bin/bash -

date

set -eu
set -o pipefail


DATE=`date +'%Y-%m-%d'`

(echo
 echo Starting new Chado load at: `date`
 echo
 cd $HOME/jbuild

 (cd japonicus-build; git pull)

 time bash ./japonicus-build/load-all.sh 'localhost' $DATE kmr44 kmr44 v62 2017-01-30 ) 2>&1 |
   tee /var/www/pombase/japonicus_nightly/builds/load-logs/$DATE.log |
   tee -a /var/pomcur/logs/nightly_japonicus_load.log

